# Generated by Django 4.0.4 on 2022-05-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endtime',
            field=models.BooleanField(default=False),
        ),
    ]
